# Generated by Django 3.2.6 on 2021-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=120)),
                ('room_no', models.CharField(max_length=10)),
                ('subjects', models.CharField(choices=[('english', 'English'), ('maths', 'Maths')], max_length=120)),
            ],
        ),
    ]
