# Generated by Django 3.2.6 on 2021-08-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_pizza_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teachers',
            name='slug',
            field=models.SlugField(blank=True, max_length=230, unique=True),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
