# Generated by Django 3.2.6 on 2021-08-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20210828_0122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
