# Generated by Django 3.2.6 on 2021-08-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_rename_teachers_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='slug',
        ),
    ]
