# Generated by Django 3.2.6 on 2021-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_teacher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(max_length=120),
        ),
    ]
