# Generated by Django 3.2.6 on 2021-08-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_alter_teacher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
