# Generated by Django 3.2.6 on 2021-08-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_alter_teacher_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/teachers/'),
        ),
    ]
